/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as StayRouteImport } from './routes/stay'
import { Route as SosRouteImport } from './routes/sos'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OrikiRouteImport } from './routes/oriki'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CeremoniesRouteImport } from './routes/ceremonies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DiscoverSlugRouteImport } from './routes/discover.$slug'
import { Route as AdminSosRouteImport } from './routes/admin.sos'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OrikiRoute = OrikiRouteImport.update({
  id: '/oriki',
  path: '/oriki',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CeremoniesRoute = CeremoniesRouteImport.update({
  id: '/ceremonies',
  path: '/ceremonies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSlugRoute = DiscoverSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiscoverRoute,
} as any)
const AdminSosRoute = AdminSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ceremonies': typeof CeremoniesRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/oriki': typeof OrikiRoute
  '/plan': typeof PlanRoute
  '/sos': typeof SosRoute
  '/stay': typeof StayRoute
  '/tickets': typeof TicketsRoute
  '/admin/sos': typeof AdminSosRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceremonies': typeof CeremoniesRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/oriki': typeof OrikiRoute
  '/plan': typeof PlanRoute
  '/sos': typeof SosRoute
  '/stay': typeof StayRoute
  '/tickets': typeof TicketsRoute
  '/admin/sos': typeof AdminSosRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ceremonies': typeof CeremoniesRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/oriki': typeof OrikiRoute
  '/plan': typeof PlanRoute
  '/sos': typeof SosRoute
  '/stay': typeof StayRoute
  '/tickets': typeof TicketsRoute
  '/admin/sos': typeof AdminSosRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ceremonies'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/learn'
    | '/oriki'
    | '/plan'
    | '/sos'
    | '/stay'
    | '/tickets'
    | '/admin/sos'
    | '/discover/$slug'
    | '/events/$slug'
    | '/experiences/$slug'
    | '/admin/'
    | '/events/'
    | '/experiences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ceremonies'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/learn'
    | '/oriki'
    | '/plan'
    | '/sos'
    | '/stay'
    | '/tickets'
    | '/admin/sos'
    | '/discover/$slug'
    | '/events/$slug'
    | '/experiences/$slug'
    | '/admin'
    | '/events'
    | '/experiences'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ceremonies'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/learn'
    | '/oriki'
    | '/plan'
    | '/sos'
    | '/stay'
    | '/tickets'
    | '/admin/sos'
    | '/discover/$slug'
    | '/events/$slug'
    | '/experiences/$slug'
    | '/admin/'
    | '/events/'
    | '/experiences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CeremoniesRoute: typeof CeremoniesRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  FaqRoute: typeof FaqRoute
  LearnRoute: typeof LearnRoute
  OrikiRoute: typeof OrikiRoute
  PlanRoute: typeof PlanRoute
  SosRoute: typeof SosRoute
  StayRoute: typeof StayRoute
  TicketsRoute: typeof TicketsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oriki': {
      id: '/oriki'
      path: '/oriki'
      fullPath: '/oriki'
      preLoaderRoute: typeof OrikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceremonies': {
      id: '/ceremonies'
      path: '/ceremonies'
      fullPath: '/ceremonies'
      preLoaderRoute: typeof CeremoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$slug': {
      id: '/discover/$slug'
      path: '/$slug'
      fullPath: '/discover/$slug'
      preLoaderRoute: typeof DiscoverSlugRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/admin/sos': {
      id: '/admin/sos'
      path: '/sos'
      fullPath: '/admin/sos'
      preLoaderRoute: typeof AdminSosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSosRoute: typeof AdminSosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSosRoute: AdminSosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DiscoverRouteChildren {
  DiscoverSlugRoute: typeof DiscoverSlugRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverSlugRoute: DiscoverSlugRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CeremoniesRoute: CeremoniesRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  FaqRoute: FaqRoute,
  LearnRoute: LearnRoute,
  OrikiRoute: OrikiRoute,
  PlanRoute: PlanRoute,
  SosRoute: SosRoute,
  StayRoute: StayRoute,
  TicketsRoute: TicketsRoute,
  EventsSlugRoute: EventsSlugRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
