/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as StayRouteImport } from './routes/stay'
import { Route as StaffAccessRouteImport } from './routes/staff-access'
import { Route as SosRouteImport } from './routes/sos'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OrikiRouteImport } from './routes/oriki'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CeremoniesRouteImport } from './routes/ceremonies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DiscoverSlugRouteImport } from './routes/discover.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminStayOwnRouteImport } from './routes/admin.stay-own'
import { Route as AdminSosRouteImport } from './routes/admin.sos'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrikiRouteImport } from './routes/admin.oriki'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLearningRouteImport } from './routes/admin.learning'
import { Route as AdminIncidentsRouteImport } from './routes/admin.incidents'
import { Route as AdminExperiencesRouteImport } from './routes/admin.experiences'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCeremoniesRouteImport } from './routes/admin.ceremonies'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as ApiPaymentsWebhooksStripeRouteImport } from './routes/api.payments.webhooks.stripe'
import { Route as ApiPaymentsWebhooksPaystackRouteImport } from './routes/api.payments.webhooks.paystack'
import { Route as ApiPaymentsWebhooksPaypalRouteImport } from './routes/api.payments.webhooks.paypal'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAccessRoute = StaffAccessRouteImport.update({
  id: '/staff-access',
  path: '/staff-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OrikiRoute = OrikiRouteImport.update({
  id: '/oriki',
  path: '/oriki',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CeremoniesRoute = CeremoniesRouteImport.update({
  id: '/ceremonies',
  path: '/ceremonies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSlugRoute = DiscoverSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiscoverRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStayOwnRoute = AdminStayOwnRouteImport.update({
  id: '/stay-own',
  path: '/stay-own',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSosRoute = AdminSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrikiRoute = AdminOrikiRouteImport.update({
  id: '/oriki',
  path: '/oriki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearningRoute = AdminLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperiencesRoute = AdminExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCeremoniesRoute = AdminCeremoniesRouteImport.update({
  id: '/ceremonies',
  path: '/ceremonies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPaymentsWebhooksStripeRoute =
  ApiPaymentsWebhooksStripeRouteImport.update({
    id: '/api/payments/webhooks/stripe',
    path: '/api/payments/webhooks/stripe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsWebhooksPaystackRoute =
  ApiPaymentsWebhooksPaystackRouteImport.update({
    id: '/api/payments/webhooks/paystack',
    path: '/api/payments/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsWebhooksPaypalRoute =
  ApiPaymentsWebhooksPaypalRouteImport.update({
    id: '/api/payments/webhooks/paypal',
    path: '/api/payments/webhooks/paypal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ceremonies': typeof CeremoniesRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/oriki': typeof OrikiRoute
  '/plan': typeof PlanRoute
  '/sos': typeof SosRoute
  '/staff-access': typeof StaffAccessRoute
  '/stay': typeof StayRoute
  '/tickets': typeof TicketsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/ceremonies': typeof AdminCeremoniesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/oriki': typeof AdminOrikiRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/stay-own': typeof AdminStayOwnRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/api/payments/webhooks/paypal': typeof ApiPaymentsWebhooksPaypalRoute
  '/api/payments/webhooks/paystack': typeof ApiPaymentsWebhooksPaystackRoute
  '/api/payments/webhooks/stripe': typeof ApiPaymentsWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceremonies': typeof CeremoniesRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/oriki': typeof OrikiRoute
  '/plan': typeof PlanRoute
  '/sos': typeof SosRoute
  '/staff-access': typeof StaffAccessRoute
  '/stay': typeof StayRoute
  '/tickets': typeof TicketsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/ceremonies': typeof AdminCeremoniesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/oriki': typeof AdminOrikiRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/stay-own': typeof AdminStayOwnRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/api/payments/webhooks/paypal': typeof ApiPaymentsWebhooksPaypalRoute
  '/api/payments/webhooks/paystack': typeof ApiPaymentsWebhooksPaystackRoute
  '/api/payments/webhooks/stripe': typeof ApiPaymentsWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ceremonies': typeof CeremoniesRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/oriki': typeof OrikiRoute
  '/plan': typeof PlanRoute
  '/sos': typeof SosRoute
  '/staff-access': typeof StaffAccessRoute
  '/stay': typeof StayRoute
  '/tickets': typeof TicketsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/ceremonies': typeof AdminCeremoniesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/oriki': typeof AdminOrikiRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/stay-own': typeof AdminStayOwnRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/api/payments/webhooks/paypal': typeof ApiPaymentsWebhooksPaypalRoute
  '/api/payments/webhooks/paystack': typeof ApiPaymentsWebhooksPaystackRoute
  '/api/payments/webhooks/stripe': typeof ApiPaymentsWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ceremonies'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/learn'
    | '/oriki'
    | '/plan'
    | '/sos'
    | '/staff-access'
    | '/stay'
    | '/tickets'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/ceremonies'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/experiences'
    | '/admin/incidents'
    | '/admin/learning'
    | '/admin/media'
    | '/admin/oriki'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/stay-own'
    | '/admin/tickets'
    | '/admin/users'
    | '/discover/$slug'
    | '/events/$slug'
    | '/experiences/$slug'
    | '/admin/'
    | '/events/'
    | '/experiences/'
    | '/api/payments/webhooks/paypal'
    | '/api/payments/webhooks/paystack'
    | '/api/payments/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ceremonies'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/learn'
    | '/oriki'
    | '/plan'
    | '/sos'
    | '/staff-access'
    | '/stay'
    | '/tickets'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/ceremonies'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/experiences'
    | '/admin/incidents'
    | '/admin/learning'
    | '/admin/media'
    | '/admin/oriki'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/stay-own'
    | '/admin/tickets'
    | '/admin/users'
    | '/discover/$slug'
    | '/events/$slug'
    | '/experiences/$slug'
    | '/admin'
    | '/events'
    | '/experiences'
    | '/api/payments/webhooks/paypal'
    | '/api/payments/webhooks/paystack'
    | '/api/payments/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ceremonies'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/learn'
    | '/oriki'
    | '/plan'
    | '/sos'
    | '/staff-access'
    | '/stay'
    | '/tickets'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/ceremonies'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/experiences'
    | '/admin/incidents'
    | '/admin/learning'
    | '/admin/media'
    | '/admin/oriki'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/stay-own'
    | '/admin/tickets'
    | '/admin/users'
    | '/discover/$slug'
    | '/events/$slug'
    | '/experiences/$slug'
    | '/admin/'
    | '/events/'
    | '/experiences/'
    | '/api/payments/webhooks/paypal'
    | '/api/payments/webhooks/paystack'
    | '/api/payments/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CeremoniesRoute: typeof CeremoniesRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  FaqRoute: typeof FaqRoute
  LearnRoute: typeof LearnRoute
  OrikiRoute: typeof OrikiRoute
  PlanRoute: typeof PlanRoute
  SosRoute: typeof SosRoute
  StaffAccessRoute: typeof StaffAccessRoute
  StayRoute: typeof StayRoute
  TicketsRoute: typeof TicketsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  ApiPaymentsWebhooksPaypalRoute: typeof ApiPaymentsWebhooksPaypalRoute
  ApiPaymentsWebhooksPaystackRoute: typeof ApiPaymentsWebhooksPaystackRoute
  ApiPaymentsWebhooksStripeRoute: typeof ApiPaymentsWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-access': {
      id: '/staff-access'
      path: '/staff-access'
      fullPath: '/staff-access'
      preLoaderRoute: typeof StaffAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oriki': {
      id: '/oriki'
      path: '/oriki'
      fullPath: '/oriki'
      preLoaderRoute: typeof OrikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceremonies': {
      id: '/ceremonies'
      path: '/ceremonies'
      fullPath: '/ceremonies'
      preLoaderRoute: typeof CeremoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$slug': {
      id: '/discover/$slug'
      path: '/$slug'
      fullPath: '/discover/$slug'
      preLoaderRoute: typeof DiscoverSlugRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stay-own': {
      id: '/admin/stay-own'
      path: '/stay-own'
      fullPath: '/admin/stay-own'
      preLoaderRoute: typeof AdminStayOwnRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sos': {
      id: '/admin/sos'
      path: '/sos'
      fullPath: '/admin/sos'
      preLoaderRoute: typeof AdminSosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/oriki': {
      id: '/admin/oriki'
      path: '/oriki'
      fullPath: '/admin/oriki'
      preLoaderRoute: typeof AdminOrikiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learning': {
      id: '/admin/learning'
      path: '/learning'
      fullPath: '/admin/learning'
      preLoaderRoute: typeof AdminLearningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents': {
      id: '/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences': {
      id: '/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminExperiencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ceremonies': {
      id: '/admin/ceremonies'
      path: '/ceremonies'
      fullPath: '/admin/ceremonies'
      preLoaderRoute: typeof AdminCeremoniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/payments/webhooks/stripe': {
      id: '/api/payments/webhooks/stripe'
      path: '/api/payments/webhooks/stripe'
      fullPath: '/api/payments/webhooks/stripe'
      preLoaderRoute: typeof ApiPaymentsWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhooks/paystack': {
      id: '/api/payments/webhooks/paystack'
      path: '/api/payments/webhooks/paystack'
      fullPath: '/api/payments/webhooks/paystack'
      preLoaderRoute: typeof ApiPaymentsWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhooks/paypal': {
      id: '/api/payments/webhooks/paypal'
      path: '/api/payments/webhooks/paypal'
      fullPath: '/api/payments/webhooks/paypal'
      preLoaderRoute: typeof ApiPaymentsWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCeremoniesRoute: typeof AdminCeremoniesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminExperiencesRoute: typeof AdminExperiencesRoute
  AdminIncidentsRoute: typeof AdminIncidentsRoute
  AdminLearningRoute: typeof AdminLearningRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrikiRoute: typeof AdminOrikiRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSosRoute: typeof AdminSosRoute
  AdminStayOwnRoute: typeof AdminStayOwnRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCeremoniesRoute: AdminCeremoniesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminExperiencesRoute: AdminExperiencesRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminLearningRoute: AdminLearningRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOrikiRoute: AdminOrikiRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSosRoute: AdminSosRoute,
  AdminStayOwnRoute: AdminStayOwnRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DiscoverRouteChildren {
  DiscoverSlugRoute: typeof DiscoverSlugRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverSlugRoute: DiscoverSlugRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CeremoniesRoute: CeremoniesRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  FaqRoute: FaqRoute,
  LearnRoute: LearnRoute,
  OrikiRoute: OrikiRoute,
  PlanRoute: PlanRoute,
  SosRoute: SosRoute,
  StaffAccessRoute: StaffAccessRoute,
  StayRoute: StayRoute,
  TicketsRoute: TicketsRoute,
  EventsSlugRoute: EventsSlugRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  ApiPaymentsWebhooksPaypalRoute: ApiPaymentsWebhooksPaypalRoute,
  ApiPaymentsWebhooksPaystackRoute: ApiPaymentsWebhooksPaystackRoute,
  ApiPaymentsWebhooksStripeRoute: ApiPaymentsWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
